---

- name: apt update and upgrade
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: Check if reboot required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: if automatic_reboot_enabled
  block:
  - name: Reboot if required
    reboot:
    when: reboot_required_file.stat.exists == true
  when: automatic_reboot_enabled == true

- name: scheduled update every 6 hours
  cron:
    name: "apt update and upgrade"
    minute: "0"
    hour: "*/6"
    job: "apt update && apt upgrade -y"
    user: root
