- name: mkdir if not exits /etc/systemd/resolved.conf.d/
  file:
    path: /etc/systemd/resolved.conf.d/
    state: directory

- name: touch /etc/systemd/resolved.conf.d/secure-dns.conf permission 0600
  file:
    path: /etc/systemd/resolved.conf.d/secure-dns.conf
    owner: root
    mode: 0640
    state: touch

- name: add line DNS=1.1.1.2 to /etc/systemd/resolved.conf.d/secure-dns.conf
  lineinfile:
    path: /etc/systemd/resolved.conf.d/secure-dns.conf
    line: "DNS=1.1.1.2" # hardcore 1.1.1.3
    state: present
    insertafter: EOF

- name: restart systemd-resolved
  systemd:
    name: systemd-resolved
    state: restarted
    enabled: yes